### ISSUE TITLE
RunError

### ISSUE THREAD

**Issue by renameart** [JiaruiFeng/KP-GNN#1]
when I command "python run_EXP_search.py" ,there is an reeor "AttributeError: 'tuple' object has no attribute 'num_nodes'  " what can i do for this error

**Comment by JiaruiFeng** [comment]
Could you provide more detail about the error? Like which line in which file raise the error. I tried to reproduce the error on both Windows/Linux but it works fine from my end.

**Comment by renameart** [comment]
> python run_EXP_search.py

Thank your reply. There is a shot about the error
![1f58b4bd6706c306bbbd6e0d71050ce](https://user-images.githubusercontent.com/61444248/202109531-1715c34b-bc2a-45ed-b21d-cb2c1d32ebe1.jpg)

**Comment by JiaruiFeng** [comment]
This is the issue with multi-GPU training. To have a quick runnable version, we temporarily blocked the multi-GPU training. You should be fine with this temporary version. It wouldn't be too slow given the size of most of dataset with a single GPU. We will update the code with multi-GPU training as soon as possible. Once it is done, we will let you know. Sorry for the inconvenience and thanks for your contribution!

**Comment by LechengKong** [comment]
Thanks! Very useful comment.

**Comment by JiaruiFeng** [comment]
Hi, please feel free to check and use our latest version, we add multi-gpu training with DataParallel in the torch. You can set multi-gpu training by adding the argument `--parallel`.

**Comment by renameart** [comment]
Tanks for your reply, you are the best open souce developer i have meet

**Comment by JiaruiFeng** [comment]
Thank you very much!
