### ISSUE TITLE
k-hop meaning

### ISSUE THREAD

**Issue by jw9603** [JiaruiFeng/KP-GNN#3]
hello.
I read your paper with interest.

In the K-hop message passing mentioned in this paper, is it correct that L-layer simply refers to the number of repetitions?
And in general, in K-hop message passing, we know that layer refers to k-hop. is this correct?

thank you

**Comment by JiaruiFeng** [comment]
Thanks for your interest in our work! I am glad to answer your questions. 
1. For the first part, yes, the L layer refers to the number of layers in the corresponding GNN model. Or you can consider it as the number of iterations/repetitions of the color update algorithm.
2. For the second part, I am not sure if I understand your question correctly. Layer in K-hop message passing refers to the same thing mentioned in the first part. Namely, the number of layers in the K-hop message passing GNN model.

If there are any further questions, please let me know!

**Comment by jw9603** [comment]
The content of the second question is as follows.
 As far as I know, the GNN (MPNN) of k layer sees k-hop neighbors, not k iterations
 
 To express it pictorially, it is as follows.
<img width="974" alt="image" src="https://github.com/JiaruiFeng/KP-GNN/assets/70795645/6c688157-eeac-4561-a6e4-e6a081c60d53">

In the figure, t is both a t-hop and a t-layer.

Thank you!!

**Comment by JiaruiFeng** [comment]
Yes, by running k layers of MPNNs, each node can obtain information from its k-hop neighbors. Instead, in k-hop message passing, each node can obtain information from its k-hop neighbors at each layer. This means, by running L layers of k-hop MPNN, each node can get information from L*k-hop neighbors. This is the main difference between the MPNNs and k-hop MPNNs. 

Therefore, I think "layer" does not refer to "k-hop" but just the times of message passing in K-hop MPNNs.

**Comment by jw9603** [comment]
If so, May i  think that there are two types of message passing neural networks?

**Comment by JiaruiFeng** [comment]
From my perspective, there are many different types of message passing neural networks. The one that people talk about the most is the one discussed in the figure you provided. In our paper, we summarized and analyzed another type of message passing neural network called K-hop message passing. 
There is a short paper discussed many different message passing neural networks: https://arxiv.org/pdf/2202.11097.pdf

Hope this would help!

**Comment by jw9603** [comment]
Thank you for replying even though you are busy!!
